In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/train.csv')

In [3]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

# Remove the units

In [6]:
df['Mileage'] = df['Mileage'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)
df['Engine'] = df['Engine'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)
df['Power'] = df['Power'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)
df['New_Price'] = df['New_Price'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

In [7]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,NaN,3.50

In [8]:
df.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

# missing values

In [9]:
missing_values = df.isnull().sum()
print("Missing_values_in_each_column:\n", missing_values)

Missing_values_in_each_column:
 Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

In [10]:
df['Mileage'].fillna(df['Mileage'].median(),inplace=True)
df['Engine'].fillna(df['Engine'].median(),inplace=True)
df['Power'].fillna(df['Power'].median(),inplace=True)

df['Seats'].fillna(df['Seats'].mode()[0],inplace=True)

df.drop('New_Price', axis=1, inplace=True)

<ipython-input-10-bf2f876a671e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Mileage'].fillna(df['Mileage'].median(),inplace=True)
<ipython-input-10-bf2f876a671e>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Engine'].fillna(df['Engine'].median(),inplace=True)
<ipython-input-10-bf2f876a671e>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Power'].fillna(df['Power'].median(),inplace=True)
<ipython-input-10-bf2f876a671e>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Seats'].fillna(df['Seats'].mode()[0],inplace=True)

In [11]:
df.isnull().sum()

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [12]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199.0,88.70,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461.0,63.10,5.0,3.50

# Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical

In [13]:
df['Fuel_Type'].replace({'Diesel': 0, 'Petrol': 1, 'Electric': 2}, inplace=True)
df['Transmission'].replace({'Manual': 0, 'Automatic': 1}, inplace=True)

<ipython-input-13-caee3d638869>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fuel_Type'].replace({'Diesel': 0, 'Petrol': 1, 'Electric': 2}, inplace=True)
<ipython-input-13-caee3d638869>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Fuel_Type'].replace({'Diesel': 0, 'Petrol': 1, 'Electric': 2}, inplace=True)
<ipython-input-13-caee3d638869>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Transmission'].replace({'Manual': 0, 'Automatic': 1}, inplace=True)
<ipython-input-13-caee3d638869>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Transmission'].replace({'Manual': 0, 'Automatic': 1}, inplace=True)

In [14]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50

# Create one more feature

In [15]:
from datetime import datetime

In [16]:
now = datetime.now().year

df['Car_Age'] = now - df['Year']

In [17]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12

# Perform select, filter, rename, mutate, arrange

In [18]:
selected_columns = df[['Fuel_Type', 'Transmission']]

In [19]:
selected_columns.head()

   Fuel_Type  Transmission
0          0             0
1          1             0
2          0             0
3          0             1
4          0             0

In [20]:
selected_columns.head()

   Fuel_Type  Transmission
0          0             0
1          1             0
2          0             0
3          0             1
4          0             0

In [21]:
filter_data = df[df['Year'] > 2010]

In [22]:
filter_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12

In [24]:
df.rename(columns={'Location': 'Place_Manufactured', 'Power': 'Horsepower'}, inplace=True)

In [25]:
df.head()

,Unnamed: 0,Name,Place_Manufactured,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Horsepower,Seats,Price,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12

In [26]:
arranged_data = df.sort_values(by='Mileage')

In [27]:
arranged_data.head()

,Unnamed: 0,Name,Place_Manufactured,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Horsepower,Seats,Price,Car_Age
5839,6011,Skoda Superb 3.6 V6 FSI,Hyderabad,2009,53000,1,1,First,0.0,3597.0,262.6,5.0,4.75,16
12,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,0,1,Second,0.0,2179.0,115.0,5.0,17.50,13
5712,5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,4000,0,1,First,0.0,1950.0,194.0,5.0,35.00,6
4172,4302,Hyundai Santro Xing GL,Delhi,2012,61449,1,0,First,0.0,1086.0,62.0,5.0,2.15,13
1339,1385,Honda City 1.5 GXI,Pune,2004,115000,1,0,Second,0.0,1497.0,98.6,5.0,1.50,21

In [28]:
summary = df.groupby('Fuel_Type')['Horsepower'].mean().reset_index()

In [29]:
summary.head()

   Fuel_Type  Horsepower
0          0  127.828966
1          1   97.123066
2          2   57.000000

In [30]:
df['Mileage_per_CC'] = df['Mileage'] / df['Engine']

In [31]:
df.head()

,Unnamed: 0,Name,Place_Manufactured,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Horsepower,Seats,Price,Car_Age,Mileage_per_CC
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582.0,126.20,5.0,12.50,10,0.012434
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199.0,88.70,5.0,4.50,14,0.010842
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248.0,88.76,7.0,6.00,13,0.016643
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968.0,140.80,5.0,17.74,12,0.007724
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461.0,63.10,5.0,3.50,12,0.015797